import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react';
import Modal from 'react-modal';

export default function Home() {

  const [modalIsOpen, setIsOpen] = React.useState(false);

  const customStyles = {
    content: {
      top: '50%',
      left: '50%',
      right: 'auto',
      bottom: 'auto',
      marginRight: '-50%',
      transform: 'translate(-50%, -50%)',
    },
  };

  const openModal = () => {
    setIsOpen(true);
  }

  const closeModal = () => {
    setIsOpen(false);
  }

  const registerEmail = (event: { preventDefault: () => void }) => {
    event.preventDefault() // don't redirect the page
    // where we'll add our form logic
    openModal()
  }

  return (
    <React.Fragment>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <h1>
          BROCCOLI & CO
        </h1>
      </header>
      <form onSubmit={registerEmail}>
      <main className={styles.main}>
        <div className={styles.grid}>
        <h1 className={styles.title}>
          A better way to enjoy everyday
        </h1>

        <p className={styles.description}>
          Be the first to know when we launch.
        </p>
        </div>
        <button className={styles.button} type="submit">Request an Invite</button>
      </main>
      </form>

      <footer className={styles.footer}>
        <div>
          <p>Made with ❤ in Melbourne. <br />
          © 2016 BROCCOLI & CO. All Rights Reserved.</p>
          </div>
      </footer>
    </div>
    <div>
      <Modal
        isOpen={modalIsOpen}
        onRequestClose={closeModal}
        style={customStyles}
        contentLabel="Example Modal"
      >
        <h2 ref={(_subtitle) => (_subtitle = _subtitle)}>Hello</h2>
        <button onClick={closeModal}>close</button>
        <div>I am a modal</div>
        <form>
          <input />
          <button>tab navigation</button>
          <button>stays</button>
          <button>inside</button>
          <button>the modal</button>
        </form>
      </Modal>
    </div>
    </React.Fragment>
  )
}
